### PR TITLE
Save info about sorting to localStorage

### PR DESCRIPTION
**Pull request by tomislater**
If you use `reload=300` in URL, you will find this change useful :P

### CODE REVIEW

**Comment by hjacobs** [comment]
SGTM

**Comment by hjacobs** [comment]
Thinking about it, the sorting should better be persisted as a query parameter (similar to "q" for the filter string) to have a "permalink".

**Comment by hjacobs** [comment]
That being said, I merged this as it's better than before. Thanks!

**Comment by tomislater** [comment]
Yeah, I was thinking about it in the same way as you, but, it would require some refactoring of select boxes.

I can do that later, it will be useful feature.

**Pull request merged**
