### PR TITLE
Add npm and webpack setup

### PR DESCRIPTION
**Pull request by shuaibiyy**
Benefits:
- Optimizes the asset generated for production.
- Allows us to take advantage of ES6 modules.
- Gives us dependency management.
- Lots more...

### CODE REVIEW

**Comment by hjacobs** [comment]
Any reason why eslintrc got removed?

**Comment by shuaibiyy** [comment]
@hjacobs eslintrc is back.

**Comment by hjacobs** [comment]
- README instructions do not work as expected (npm start runs in the foreground)
- Docker build does not add the generated app.js, please test with `docker run ...`

**Comment by hjacobs** [comment]
OK, my fault, `app.js` is there.

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
