### PR TITLE
Filter out "Evicted" pods

### LINKED ISSUE #157: Pods that fail due to eviction show up indefinitely
If a pod is terminated due to EVICTION- lets say its an OOM kill or nodefs failure, it hangs around in the dashboard forever. This is likely due to the fact that evicted pods due to cgroups issues are not "Terminated" normally so they don't get a state or termination time- thus the patch applied in #126 doesn't help

I'm not sure what to do in this case, since we cant filter it out if its an hour old. we could just add a simple always-hide via line 93 like so:
```
if (last_termination_time and last_termination_time < now - 3600) or (obj['reason'] in 'Evicted'):
```

0227181026_hdr
0227181027_hdr

### PR DESCRIPTION
**Pull request by rapenchukd**
fixes #157 
See issue for details

### CODE REVIEW

**Comment by hjacobs** [comment]
Thanks for the PR! Would it make sense to add one or more evicted pods to the mock data in order to test?

**Comment by rapenchukd** [comment]
Makes perfect sense! ill get that added later today

**Comment by rapenchukd** [comment]
Does this look good?

**Comment by hjacobs** [comment]
:+1:

**Pull request merged**
