### PR TITLE
Tooltip for node bars

### PR DESCRIPTION
**Pull request by ChristianLohmann**
please don't delete the branch

### CODE REVIEW

**Comment by hjacobs** [comment]
There are some eslint errors and I would like to avoid the trailing semicolon..

**Comment by hjacobs** [comment]
Please explain how it works with the `nodejs-socket` stuff, at least for me it does not work out of the box (running "npm start" in app and starting "/app.py").

**Comment by ChristianLohmann** [comment]
removed that sockjs-node stuff; added eslint preloader --> when running app with webpack every hot reload will be linted before

**Comment by hjacobs** [comment]
@ChristianLohmann thanks!

**Pull request merged**
